echo "acme-apache2 1.0 ___ Welcome___v.1"
echo "NEW cert Request and gen"
echo "how to use ang gen ssl --help solud a command options"
echo " "
echo "--domain  == Enter the name in the room for which you want to generate TLS/SSL  certificate (e.g.,webhost.com) you can also use the name of the subdomain (e.g.,anthor.domain.com)"
echo " "
echo "--subj    == countryName,state_name,localityName,orgname,organizationalUnitName"
echo "            Pattern:C,ST,L,O,OU"   

echo "            --subj IN,Rajthan,city,oragtion,organizationalUnitName"
echo " "
echo "--conf   ==   base/dir Where httpd Site Visiting Sites conf Is Available Cake"
echo "              (e.g.,) /sdk-srvar/apache2/usr/conf/sites,  or/sdk-srvar/apache2/usr/conf/sites-enabled"
echo "             find error fix this sites-enabled/mysite.com/mysite.com.conf"
echo " "
echo "--subd   ==   subdomain,include the word menu with menu man same certificate subdomain , enter the name of all those you want to get certificate  "
echo "              (e.g.,) --subd 1.test.com,2.test.com"
echo " "